version: '3'

services:
  db-mysql:
    image: mysql:5.7
    container_name: mysql_for_geo
    restart: always
    environment:
      MYSQL_DATABASE: 'findhotel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
